build { core
        init
        lib/ld
        lib/libc
        lib/libm
        lib/vfs
        lib/posix
        test/fork_after_execve
        lib/test_shared
}

create_boot_directory


install_config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>

	<default-route> <any-service> <parent/> </any-service> </default-route>
	<default caps="200"/>
	<start name="test-fork_after_execve" caps="1500" ram="10M">
		<config ld_verbose="yes">
			<arg value="test-fork_after_execve"/>
			<arg value="0"/>
			<libc stdin="/null" stdout="/log" stderr="/log"/>
			<vfs>
				<null/> <log/>
				<rom name="test-fork_after_execve"/>
			</vfs>
		</config>
		<route>
			<service name="ROM" label="/test-fork_after_execve">
				<parent label="test-fork_after_execve"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>
</config>
}

build_boot_image [build_artifacts]

append qemu_args " -nographic  "

run_genode_until forever

