#
# Build
#

build { core lib/ld init hello }

create_boot_directory

#
# Generate config
#

install_config {
config
+ parent-provides
  + service LOG
  + service PD
  + service CPU
  + service ROM

+ default-route
  + any-service
    + parent
    + any-child
+ default | caps: 60 | ram: 1M

+ start hello_server
  + provides | + service Hello

+ start hello_client
-
}

#
# Boot image
#

build_boot_image [build_artifacts]

append qemu_args " -nographic "

run_genode_until "hello test completed.*\n" 10
