LIB_MK := $(addprefix lib/mk/, \
            nbconfig.mk \
            rump_common.inc \
            rump_fs.mk \
            rump.inc \
            rump_include.inc \
            rump_prefix.inc \
            rump_tools.mk \
            vfs_rump.mk) \
          $(foreach SPEC,x86_32 x86_64 arm, \
            lib/mk/spec/$(SPEC)/rump.mk \
            lib/mk/spec/$(SPEC)/rump_include.mk)

PORT_DIR := $(call port_dir,$(REP_DIR)/ports/dde_rump)

MIRROR_FROM_REP_DIR := $(LIB_MK) \
                       lib/import/import-rump.mk \
                       src/ld src/lib src/server/rump_fs \
                       include/rump include/rump_fs \
                       include/util

PORT_FILES := src/common/include/ppath/ppath.h \
              src/common/include/ppath/ppath_impl.h \
              src/common/include/prop/plistref.h \
              src/common/include/prop/prop_array.h \
              src/common/include/prop/prop_bool.h \
              src/common/include/prop/prop_data.h \
              src/common/include/prop/prop_dictionary.h \
              src/common/include/prop/prop_ingest.h \
              src/common/include/prop/proplib.h \
              src/common/include/prop/prop_number.h \
              src/common/include/prop/prop_object.h \
              src/common/include/prop/prop_string.h \
              src/common/lib/libc/arch/arm/atomic/atomic_add_32.S \
              src/common/lib/libc/arch/arm/atomic/atomic_and_32.S \
              src/common/lib/libc/arch/arm/atomic/atomic_cas_32.S \
              src/common/lib/libc/arch/arm/atomic/atomic_dec_32.S \
              src/common/lib/libc/arch/arm/atomic/atomic_inc_32.S \
              src/common/lib/libc/arch/arm/atomic/atomic_op_asm.h \
              src/common/lib/libc/arch/arm/atomic/atomic_or_32.S \
              src/common/lib/libc/arch/arm/atomic/atomic_swap.S \
              src/common/lib/libc/arch/arm/atomic/membar_ops.S \
              src/common/lib/libc/arch/i386/atomic/atomic.S \
              src/common/lib/libc/arch/x86_64/atomic/atomic.S \
              src/common/lib/libc/arch/x86_64/gen/byte_swap_2.S \
              src/common/lib/libc/arch/x86_64/gen/byte_swap_4.S \
              src/common/lib/libc/arch/x86_64/gen/byte_swap_8.S \
              src/common/lib/libc/cdb/cdbr.c \
              src/common/lib/libc/gen/bswap32.c \
              src/common/lib/libc/gen/bswap64.c \
              src/common/lib/libc/gen/ptree.c \
              src/common/lib/libc/gen/rb.c \
              src/common/lib/libc/gmon/mcount.c \
              src/common/lib/libc/hash/murmurhash/murmurhash.c \
              src/common/lib/libc/hash/rmd160/rmd160.c \
              src/common/lib/libc/hash/sha1/sha1.c \
              src/common/lib/libc/hash/sha2/sha2.c \
              src/common/lib/libc/inet/inet_addr.c \
              src/common/lib/libc/md/md4c.c \
              src/common/lib/libc/md/md5c.c \
              src/common/lib/libc/stdlib/heapsort.c \
              src/common/lib/libc/stdlib/mi_vector_hash.c \
              src/common/lib/libc/stdlib/random.c \
              src/common/lib/libc/stdlib/strtoimax.c \
              src/common/lib/libc/stdlib/_strtol.h \
              src/common/lib/libc/stdlib/strtoll.c \
              src/common/lib/libc/stdlib/strtoul.c \
              src/common/lib/libc/stdlib/_strtoul.h \
              src/common/lib/libc/stdlib/strtoull.c \
              src/common/lib/libc/stdlib/strtoumax.c \
              src/common/lib/libc/string/bcopy.c \
              src/common/lib/libc/string/consttime_memequal.c \
              src/common/lib/libc/string/explicit_memset.c \
              src/common/lib/libc/string/ffs.c \
              src/common/lib/libc/string/memchr.c \
              src/common/lib/libc/string/memcmp.c \
              src/common/lib/libc/string/memcpy.c \
              src/common/lib/libc/string/memmove.c \
              src/common/lib/libc/string/memset.c \
              src/common/lib/libc/string/popcount32.c \
              src/common/lib/libc/string/popcount64.c \
              src/common/lib/libc/string/strcasecmp.c \
              src/common/lib/libc/string/strcat.c \
              src/common/lib/libc/string/strchr.c \
              src/common/lib/libc/string/strcmp.c \
              src/common/lib/libc/string/strcpy.c \
              src/common/lib/libc/string/strcspn.c \
              src/common/lib/libc/string/strlcat.c \
              src/common/lib/libc/string/strlcpy.c \
              src/common/lib/libc/string/strlen.c \
              src/common/lib/libc/string/strncasecmp.c \
              src/common/lib/libc/string/strncat.c \
              src/common/lib/libc/string/strncmp.c \
              src/common/lib/libc/string/strncpy.c \
              src/common/lib/libc/string/strnlen.c \
              src/common/lib/libc/string/strpbrk.c \
              src/common/lib/libc/string/strrchr.c \
              src/common/lib/libc/string/strsep.c \
              src/common/lib/libc/string/strspn.c \
              src/common/lib/libc/string/strstr.c \
              src/common/lib/libc/sys/cpuset.c \
              src/common/lib/libppath/ppath.c \
              src/common/lib/libppath/ppath_extant.c \
              src/common/lib/libppath/ppath_kmem_alloc.c \
              src/common/lib/libprop/prop_array.c \
              src/common/lib/libprop/prop_array_util.c \
              src/common/lib/libprop/prop_bool.c \
              src/common/lib/libprop/prop_data.c \
              src/common/lib/libprop/prop_dictionary.c \
              src/common/lib/libprop/prop_dictionary_util.c \
              src/common/lib/libprop/prop_ingest.c \
              src/common/lib/libprop/prop_kern.c \
              src/common/lib/libprop/prop_number.c \
              src/common/lib/libprop/prop_object.c \
              src/common/lib/libprop/prop_object_impl.h \
              src/common/lib/libprop/prop_rb_impl.h \
              src/common/lib/libprop/prop_stack.c \
              src/common/lib/libprop/prop_stack.h \
              src/common/lib/libprop/prop_string.c \
              src/common/lib/libutil/getfstypename.c \
              src/common/lib/libutil/proc_compare.c \
              src/common/lib/libutil/snprintb.c \
              src/include/stdbool.h \
              src/lib/rump/bootstrap.cc \
              src/lib/rump/dummies.cc \
              src/lib/rump/env.cc \
              src/lib/rump/hypercall.cc \
              src/lib/rump/io.cc \
              src/lib/rump/misc.cc \
              src/lib/rump/sched.h \
              src/lib/rump/sync.cc \
              src/server/rump2_fs/directory.h \
              src/server/rump2_fs/file.h \
              src/server/rump2_fs/file_system.cc \
              src/server/rump2_fs/file_system.h \
              src/server/rump2_fs/main.cc \
              src/server/rump2_fs/node.h \
              src/server/rump2_fs/random.cc \
              src/server/rump2_fs/symlink.h \
              src/server/rump2_fs/undef.h \
              src/server/rump_fs/directory.h \
              src/server/rump_fs/file.h \
              src/server/rump_fs/file_system.cc \
              src/server/rump_fs/file_system.h \
              src/server/rump_fs/main.cc \
              src/server/rump_fs/node.h \
              src/server/rump_fs/random.cc \
              src/server/rump_fs/symlink.h \
              src/server/rump_fs/undef.h \
              src/sys/altq/if_altq.h \
              src/sys/arch/amd64/amd64/kobj_machdep.c \
              src/sys/arch/arm/arm32/kobj_machdep.c \
              src/sys/arch/i386/i386/kobj_machdep.c \
              src/sys/compat/common/compat_mod.h \
              src/sys/compat/common/compat_util.h \
              src/sys/compat/common/kern_select_50.c \
              src/sys/compat/common/kern_time_50.c \
              src/sys/compat/common/vfs_syscalls_50.c \
              src/sys/compat/sys/clockctl.h \
              src/sys/compat/sys/dirent.h \
              src/sys/compat/sys/mount.h \
              src/sys/compat/sys/resource.h \
              src/sys/compat/sys/stat.h \
              src/sys/compat/sys/time.h \
              src/sys/compat/sys/time_types.h \
              src/sys/compat/sys/timex.h \
              src/sys/conf/param.c \
              src/sys/crypto/cprng_fast/cprng_fast.c \
              src/sys/crypto/cprng_fast/cprng_fast.h \
              src/sys/crypto/nist_ctr_drbg/nist_ctr_aes_rijndael.h \
              src/sys/crypto/nist_ctr_drbg/nist_ctr_drbg_aes128.h \
              src/sys/crypto/nist_ctr_drbg/nist_ctr_drbg.c \
              src/sys/crypto/nist_ctr_drbg/nist_ctr_drbg_config.h \
              src/sys/crypto/nist_ctr_drbg/nist_ctr_drbg.h \
              src/sys/crypto/rijndael/rijndael-alg-fst.c \
              src/sys/crypto/rijndael/rijndael-alg-fst.h \
              src/sys/crypto/rijndael/rijndael-api-fst.c \
              src/sys/crypto/rijndael/rijndael-api-fst.h \
              src/sys/crypto/rijndael/rijndael.c \
              src/sys/crypto/rijndael/rijndael.h \
              src/sys/crypto/rijndael/rijndael_local.h \
              src/sys/dev/clock_subr.c \
              src/sys/dev/clock_subr.h \
              src/sys/dev/cons.c \
              src/sys/dev/cons.h \
              src/sys/dev/dksubr.c \
              src/sys/dev/dkvar.h \
              src/sys/dev/dkwedge/dk.c \
              src/sys/dev/firmload.c \
              src/sys/dev/firmload.h \
              src/sys/dev/rnd_private.h \
              src/sys/dev/../sys/clock.h \
              src/sys/fs/cd9660/cd9660_bmap.c \
              src/sys/fs/cd9660/cd9660_extern.h \
              src/sys/fs/cd9660/cd9660_lookup.c \
              src/sys/fs/cd9660/cd9660_mount.h \
              src/sys/fs/cd9660/cd9660_node.c \
              src/sys/fs/cd9660/cd9660_node.h \
              src/sys/fs/cd9660/cd9660_rrip.c \
              src/sys/fs/cd9660/cd9660_rrip.h \
              src/sys/fs/cd9660/cd9660_util.c \
              src/sys/fs/cd9660/cd9660_vfsops.c \
              src/sys/fs/cd9660/cd9660_vnops.c \
              src/sys/fs/cd9660/iso.h \
              src/sys/fs/cd9660/iso_rrip.h \
              src/sys/fs/msdosfs/bootsect.h \
              src/sys/fs/msdosfs/bpb.h \
              src/sys/fs/msdosfs/denode.h \
              src/sys/fs/msdosfs/direntry.h \
              src/sys/fs/msdosfs/fat.h \
              src/sys/fs/msdosfs/msdosfs_conv.c \
              src/sys/fs/msdosfs/msdosfs_denode.c \
              src/sys/fs/msdosfs/msdosfs_fat.c \
              src/sys/fs/msdosfs/msdosfs_lookup.c \
              src/sys/fs/msdosfs/msdosfsmount.h \
              src/sys/fs/msdosfs/msdosfs_vfsops.c \
              src/sys/fs/msdosfs/msdosfs_vnops.c \
              src/sys/fs/udf/ecma167-udf.h \
              src/sys/fs/unicode.h \
              src/sys/kern/bufq_disksort.c \
              src/sys/kern/bufq_fcfs.c \
              src/sys/kern/bufq_priocscan.c \
              src/sys/kern/bufq_readprio.c \
              src/sys/kern/init_sysctl_base.c \
              src/sys/kern/kern_auth.c \
              src/sys/kern/kern_cfglock.c \
              src/sys/kern/kern_descrip.c \
              src/sys/kern/kern_event.c \
              src/sys/kern/kern_hook.c \
              src/sys/kern/kern_ksyms.c \
              src/sys/kern/kern_ktrace.c \
              src/sys/kern/kern_ktrace_vfs.c \
              src/sys/kern/kern_malloc.c \
              src/sys/kern/kern_module.c \
              src/sys/kern/kern_module_vfs.c \
              src/sys/kern/kern_mutex_obj.c \
              src/sys/kern/kern_ntptime.c \
              src/sys/kern/kern_physio.c \
              src/sys/kern/kern_pmf.c \
              src/sys/kern/kern_proc.c \
              src/sys/kern/kern_prot.c \
              src/sys/kern/kern_rate.c \
              src/sys/kern/kern_resource.c \
              src/sys/kern/kern_rndpool.c \
              src/sys/kern/kern_rndq.c \
              src/sys/kern/kern_rndsink.c \
              src/sys/kern/kern_stub.c \
              src/sys/kern/kern_syscall.c \
              src/sys/kern/kern_sysctl.c \
              src/sys/kern/kern_tc.c \
              src/sys/kern/kern_time.c \
              src/sys/kern/kern_timeout.c \
              src/sys/kern/kern_uidinfo.c \
              src/sys/kern/kern_xxx.c \
              src/sys/kern/subr_autoconf.c \
              src/sys/kern/subr_bufq.c \
              src/sys/kern/subr_callback.c \
              src/sys/kern/subr_copy.c \
              src/sys/kern/subr_cprng.c \
              src/sys/kern/subr_device.c \
              src/sys/kern/subr_devsw.c \
              src/sys/kern/subr_disk.c \
              src/sys/kern/subr_disk_mbr.c \
              src/sys/kern/subr_disk_open.c \
              src/sys/kern/subr_evcnt.c \
              src/sys/kern/subr_extent.c \
              src/sys/kern/subr_hash.c \
              src/sys/kern/subr_humanize.c \
              src/sys/kern/subr_iostat.c \
              src/sys/kern/subr_kcpuset.c \
              src/sys/kern/subr_kmem.c \
              src/sys/kern/subr_kobj.c \
              src/sys/kern/subr_kobj_vfs.c \
              src/sys/kern/subr_log.c \
              src/sys/kern/subr_lwp_specificdata.c \
              src/sys/kern/subr_once.c \
              src/sys/kern/subr_pcq.c \
              src/sys/kern/subr_percpu.c \
              src/sys/kern/subr_pool.c \
              src/sys/kern/subr_prf.c \
              src/sys/kern/subr_pserialize.c \
              src/sys/kern/subr_specificdata.c \
              src/sys/kern/subr_time.c \
              src/sys/kern/subr_vmem.c \
              src/sys/kern/subr_workqueue.c \
              src/sys/kern/subr_xcall.c \
              src/sys/kern/syscalls.c \
              src/sys/kern/sys_descrip.c \
              src/sys/kern/sys_generic.c \
              src/sys/kern/sys_module.c \
              src/sys/kern/sys_pipe.c \
              src/sys/kern/sys_select.c \
              src/sys/kern/sys_syscall.c \
              src/sys/kern/uipc_sem.c \
              src/sys/kern/vfs_bio.c \
              src/sys/kern/vfs_cache.c \
              src/sys/kern/vfs_cwd.c \
              src/sys/kern/vfs_dirhash.c \
              src/sys/kern/vfs_getcwd.c \
              src/sys/kern/vfs_hooks.c \
              src/sys/kern/vfs_init.c \
              src/sys/kern/vfs_lockf.c \
              src/sys/kern/vfs_lookup.c \
              src/sys/kern/vfs_mount.c \
              src/sys/kern/vfs_quotactl.c \
              src/sys/kern/vfs_subr.c \
              src/sys/kern/vfs_syscalls.c \
              src/sys/kern/vfs_trans.c \
              src/sys/kern/vfs_vnode.c \
              src/sys/kern/vfs_vnops.c \
              src/sys/kern/vfs_wapbl.c \
              src/sys/kern/vfs_xattr.c \
              src/sys/kern/vnode_if.c \
              src/sys/lib/libkern/crc32.c \
              src/sys/lib/libkern/crc32.h \
              src/sys/lib/libkern/imax.c \
              src/sys/lib/libkern/imin.c \
              src/sys/lib/libkern/intoa.c \
              src/sys/lib/libkern/kern_assert.c \
              src/sys/lib/libkern/libkern.h \
              src/sys/lib/libkern/lmax.c \
              src/sys/lib/libkern/lmin.c \
              src/sys/lib/libkern/__main.c \
              src/sys/lib/libkern/max.c \
              src/sys/lib/libkern/mertwist.c \
              src/sys/lib/libkern/min.c \
              src/sys/lib/libkern/pmatch.c \
              src/sys/lib/libkern/rngtest.c \
              src/sys/lib/libkern/scanc.c \
              src/sys/lib/libkern/skpc.c \
              src/sys/lib/libkern/ulmax.c \
              src/sys/lib/libkern/ulmin.c \
              src/sys/lib/libkern/xlat_mbr_fstype.c \
              src/sys/miscfs/deadfs/dead_vfsops.c \
              src/sys/miscfs/deadfs/dead_vnops.c \
              src/sys/miscfs/fifofs/fifo.h \
              src/sys/miscfs/genfs/genfs.h \
              src/sys/miscfs/genfs/genfs_io.c \
              src/sys/miscfs/genfs/genfs_node.h \
              src/sys/miscfs/genfs/genfs_rename.c \
              src/sys/miscfs/genfs/genfs_vfsops.c \
              src/sys/miscfs/genfs/genfs_vnops.c \
              src/sys/miscfs/specfs/specdev.h \
              src/sys/miscfs/specfs/spec_vnops.c \
              src/sys/miscfs/syncfs/syncfs.h \
              src/sys/miscfs/syncfs/sync_subr.c \
              src/sys/miscfs/syncfs/sync_vnops.c \
              src/sys/net/dlt.h \
              src/sys/net/if_arp.h \
              src/sys/net/if.h \
              src/sys/netinet6/in6.h \
              src/sys/netinet/in.h \
              src/sys/net/pfil.h \
              src/sys/net/pktqueue.h \
              src/sys/nfs/nfs.h \
              src/sys/nfs/nfsproto.h \
              src/sys/nfs/nfs_var.h \
              src/sys/nfs/rpcv2.h \
              src/sys/rump/include/machine/cpu.h \
              src/sys/rump/include/machine/intr.h \
              src/sys/rump/include/machine/pmap.h \
              src/sys/rump/include/rump/rumpdefs.h \
              src/sys/rump/include/rump/rump.h \
              src/sys/rump/include/rump/rumpkern_if_pub.h \
              src/sys/rump/include/rump/rump_namei.h \
              src/sys/rump/include/rump/rumpnet_if_pub.h \
              src/sys/rump/include/rump/rump_syscalls_compat.h \
              src/sys/rump/include/rump/rump_syscalls.h \
              src/sys/rump/include/rump/rumpuser.h \
              src/sys/rump/include/rump/rumpvfs_if_pub.h \
              src/sys/rump/include/rump/rumpvnode_if.h \
              src/sys/rump/include/sys/bus.h \
              src/sys/rump/librump/rumpdev/autoconf.c \
              src/sys/rump/librump/rumpdev/opt/wsdisplay.h \
              src/sys/rump/librump/rumpdev/rump_dev.c \
              src/sys/rump/librump/rumpdev/rump_dev_private.h \
              src/sys/rump/librump/rumpkern/accessors.c \
              src/sys/rump/librump/rumpkern/arch/generic/rump_generic_cpu.c \
              src/sys/rump/librump/rumpkern/arch/generic/rump_generic_pmap.c \
              src/sys/rump/librump/rumpkern/arch/x86/rump_x86_cpu.c \
              src/sys/rump/librump/rumpkern/arch/x86/rump_x86_cpu_counter.c \
              src/sys/rump/librump/rumpkern/arch/x86/rump_x86_pmap.c \
              src/sys/rump/librump/rumpkern/arch/x86/rump_x86_spinlock.c \
              src/sys/rump/librump/rumpkern/arch/x86/rump_x86_spl.c \
              src/sys/rump/librump/rumpkern/cons.c \
              src/sys/rump/librump/rumpkern/devsw.c \
              src/sys/rump/librump/rumpkern/emul.c \
              src/sys/rump/librump/rumpkern/etfs_wrap.c \
              src/sys/rump/librump/rumpkern/hyperentropy.c \
              src/sys/rump/librump/rumpkern/intr.c \
              src/sys/rump/librump/rumpkern/klock.c \
              src/sys/rump/librump/rumpkern/kobj_rename.c \
              src/sys/rump/librump/rumpkern/locks_up.c \
              src/sys/rump/librump/rumpkern/ltsleep.c \
              src/sys/rump/librump/rumpkern/lwproc.c \
              src/sys/rump/librump/rumpkern/opt/config_file.h \
              src/sys/rump/librump/rumpkern/opt/ksyms.h \
              src/sys/rump/librump/rumpkern/opt/opt_bufcache.h \
              src/sys/rump/librump/rumpkern/opt/opt_compat_43.h \
              src/sys/rump/librump/rumpkern/opt/opt_compat_netbsd.h \
              src/sys/rump/librump/rumpkern/opt/opt_ddb.h \
              src/sys/rump/librump/rumpkern/opt/opt_defcorename.h \
              src/sys/rump/librump/rumpkern/opt/opt_dump.h \
              src/sys/rump/librump/rumpkern/opt/opt_hz.h \
              src/sys/rump/librump/rumpkern/opt/opt_ipkdb.h \
              src/sys/rump/librump/rumpkern/opt/opt_kgdb.h \
              src/sys/rump/librump/rumpkern/opt/opt_ktrace.h \
              src/sys/rump/librump/rumpkern/opt/opt_lockdebug.h \
              src/sys/rump/librump/rumpkern/opt/opt_magiclinks.h \
              src/sys/rump/librump/rumpkern/opt/opt_modular.h \
              src/sys/rump/librump/rumpkern/opt/opt_multiprocessor.h \
              src/sys/rump/librump/rumpkern/opt/opt_ptrace.h \
              src/sys/rump/librump/rumpkern/opt/opt_revcache.h \
              src/sys/rump/librump/rumpkern/opt/opt_rnd_printf.h \
              src/sys/rump/librump/rumpkern/opt/opt_rtc_offset.h \
              src/sys/rump/librump/rumpkern/opt/opt_sysv.h \
              src/sys/rump/librump/rumpkern/opt/opt_sysvparam.h \
              src/sys/rump/librump/rumpkern/opt/opt_uvmhist.h \
              src/sys/rump/librump/rumpkern/opt/veriexec.h \
              src/sys/rump/librump/rumpkern/rump.c \
              src/sys/rump/librump/rumpkern/rumpcopy.c \
              src/sys/rump/librump/rumpkern/rump_curlwp.h \
              src/sys/rump/librump/rumpkern/rump_curlwp_hypercall.h \
              src/sys/rump/librump/rumpkern/rumpkern_if_priv.h \
              src/sys/rump/librump/rumpkern/rumpkern_if_wrappers.c \
              src/sys/rump/librump/rumpkern/rumpkern_syscalls.c \
              src/sys/rump/librump/rumpkern/rump_private.h \
              src/sys/rump/librump/rumpkern/rump_syscalls.c \
              src/sys/rump/librump/rumpkern/scheduler.c \
              src/sys/rump/librump/rumpkern/signals.c \
              src/sys/rump/librump/rumpkern/sleepq.c \
              src/sys/rump/librump/rumpkern/threads.c \
              src/sys/rump/librump/rumpkern/vm.c \
              src/sys/rump/librump/rumpnet/rumpnet_if_priv.h \
              src/sys/rump/librump/rumpnet/rump_net_private.h \
              src/sys/rump/librump/rumpvfs/compat.c \
              src/sys/rump/librump/rumpvfs/devnodes.c \
              src/sys/rump/librump/rumpvfs/devnull.c \
              src/sys/rump/librump/rumpvfs/rumpblk.c \
              src/sys/rump/librump/rumpvfs/rumpfs.c \
              src/sys/rump/librump/rumpvfs/rump_vfs.c \
              src/sys/rump/librump/rumpvfs/rumpvfs_if_priv.h \
              src/sys/rump/librump/rumpvfs/rumpvfs_if_wrappers.c \
              src/sys/rump/librump/rumpvfs/rump_vfs_private.h \
              src/sys/rump/librump/rumpvfs/rumpvfs_syscalls.c \
              src/sys/rump/librump/rumpvfs/rumpvnode_if.c \
              src/sys/rump/librump/rumpvfs/vm_vfs.c \
              src/sys/secmodel/secmodel.c \
              src/sys/secmodel/secmodel.h \
              src/sys/secmodel/suser/secmodel_suser.c \
              src/sys/secmodel/suser/suser.h \
              src/sys/sys/acct.h \
              src/sys/sys/aio.h \
              src/sys/sys/ansi.h \
              src/sys/sys/atomic.h \
              src/sys/sys/bitops.h \
              src/sys/sys/bootblock.h \
              src/sys/sys/bswap.h \
              src/sys/sys/buf.h \
              src/sys/sys/bufq.h \
              src/sys/sys/bufq_impl.h \
              src/sys/sys/bus.h \
              src/sys/sys/bus_proto.h \
              src/sys/sys/callback.h \
              src/sys/sys/callout.h \
              src/sys/sys/cdbr.h \
              src/sys/sys/cdefs_elf.h \
              src/sys/sys/cdefs.h \
              src/sys/sys/cdio.h \
              src/sys/sys/clockctl.h \
              src/sys/sys/clock.h \
              src/sys/sys/common_int_limits.h \
              src/sys/sys/common_int_mwgwtypes.h \
              src/sys/sys/common_int_types.h \
              src/sys/sys/condvar.h \
              src/sys/sys/conf.h \
              src/sys/sys/cprng.h \
              src/sys/sys/cpu_data.h \
              src/sys/sys/cpu.h \
              src/sys/sys/debug.h \
              src/sys/sys/device.h \
              src/sys/sys/device_if.h \
              src/sys/sys/devmon.h \
              src/sys/sys/dirent.h \
              src/sys/sys/dirhash.h \
              src/sys/sys/disk.h \
              src/sys/sys/disklabel_acorn.h \
              src/sys/sys/disklabel.h \
              src/sys/sys/dkbad.h \
              src/sys/sys/dkio.h \
              src/sys/sys/dtrace_bsd.h \
              src/sys/sys/endian.h \
              src/sys/sys/errno.h \
              src/sys/sys/evcnt.h \
              src/sys/sys/event.h \
              src/sys/sys/eventvar.h \
              src/sys/sys/exec_elf.h \
              src/sys/sys/exec.h \
              src/sys/sys/extattr.h \
              src/sys/sys/extent.h \
              src/sys/sys/fcntl.h \
              src/sys/sys/fd_set.h \
              src/sys/sys/featuretest.h \
              src/sys/sys/filedesc.h \
              src/sys/sys/file.h \
              src/sys/sys/filio.h \
              src/sys/sys/fstrans.h \
              src/sys/sys/fstypes.h \
              src/sys/sys/hash.h \
              src/sys/sys/intr.h \
              src/sys/sys/inttypes.h \
              src/sys/sys/ioccom.h \
              src/sys/sys/ioctl_compat.h \
              src/sys/sys/ioctl.h \
              src/sys/sys/iostat.h \
              src/sys/sys/ipi.h \
              src/sys/sys/kauth.h \
              src/sys/sys/kcpuset.h \
              src/sys/sys/kernel.h \
              src/sys/sys/kernhist.h \
              src/sys/sys/kmem.h \
              src/sys/sys/kobj.h \
              src/sys/sys/kobj_impl.h \
              src/sys/sys/kprintf.h \
              src/sys/sys/ksem.h \
              src/sys/sys/ksyms.h \
              src/sys/sys/kthread.h \
              src/sys/sys/ktrace.h \
              src/sys/sys/lockdebug.h \
              src/sys/sys/lockf.h \
              src/sys/sys/lock.h \
              src/sys/sys/lwp.h \
              src/sys/sys/malloc.h \
              src/sys/sys/mallocvar.h \
              src/sys/sys/mbuf.h \
              src/sys/sys/md4.h \
              src/sys/sys/md5.h \
              src/sys/sys/mman.h \
              src/sys/sys/module.h \
              src/sys/sys/mount.h \
              src/sys/sys/mqueue.h \
              src/sys/sys/msgbuf.h \
              src/sys/sys/mutex.h \
              src/sys/sys/namei.h \
              src/sys/sys/null.h \
              src/sys/sys/once.h \
              src/sys/sys/param.h \
              src/sys/sys/pcq.h \
              src/sys/sys/pcu.h \
              src/sys/sys/percpu.h \
              src/sys/sys/percpu_types.h \
              src/sys/sys/pipe.h \
              src/sys/sys/pmf.h \
              src/sys/sys/poll.h \
              src/sys/sys/pool.h \
              src/sys/sys/proc.h \
              src/sys/sys/prot.h \
              src/sys/sys/protosw.h \
              src/sys/sys/pserialize.h \
              src/sys/sys/pset.h \
              src/sys/sys/ptrace.h \
              src/sys/sys/ptree.h \
              src/sys/sys/queue.h \
              src/sys/sys/quotactl.h \
              src/sys/sys/quota.h \
              src/sys/sys/ras.h \
              src/sys/sys/rbtree.h \
              src/sys/sys/reboot.h \
              src/sys/sys/resource.h \
              src/sys/sys/resourcevar.h \
              src/sys/sys/rmd160.h \
              src/sys/sys/rnd.h \
              src/sys/sys/rndsink.h \
              src/sys/sys/rngtest.h \
              src/sys/sys/rwlock.h \
              src/sys/sys/sched.h \
              src/sys/sys/select.h \
              src/sys/sys/selinfo.h \
              src/sys/sys/sha1.h \
              src/sys/sys/sha2.h \
              src/sys/sys/siginfo.h \
              src/sys/sys/signal.h \
              src/sys/sys/signalvar.h \
              src/sys/sys/sigtypes.h \
              src/sys/sys/sleepq.h \
              src/sys/sys/socket.h \
              src/sys/sys/socketvar.h \
              src/sys/sys/sockio.h \
              src/sys/sys/specificdata.h \
              src/sys/sys/spldebug.h \
              src/sys/sys/spl.h \
              src/sys/sys/stat.h \
              src/sys/sys/statvfs.h \
              src/sys/sys/stdarg.h \
              src/sys/sys/stdint.h \
              src/sys/sys/syncobj.h \
              src/sys/sys/syscallargs.h \
              src/sys/sys/syscall.h \
              src/sys/sys/syscall_stats.h \
              src/sys/sys/syscallvar.h \
              src/sys/sys/sysctl.h \
              src/sys/sys/syslimits.h \
              src/sys/sys/syslog.h \
              src/sys/sys/systm.h \
              src/sys/sys/termios.h \
              src/sys/sys/timeb.h \
              src/sys/sys/time.h \
              src/sys/sys/timepps.h \
              src/sys/sys/times.h \
              src/sys/sys/timetc.h \
              src/sys/sys/timevar.h \
              src/sys/sys/timex.h \
              src/sys/sys/tprintf.h \
              src/sys/sys/trace.h \
              src/sys/sys/tree.h \
              src/sys/sys/ttychars.h \
              src/sys/sys/ttycom.h \
              src/sys/sys/ttydefaults.h \
              src/sys/sys/ttydev.h \
              src/sys/sys/tty.h \
              src/sys/sys/types.h \
              src/sys/sys/ucontext.h \
              src/sys/sys/ucred.h \
              src/sys/sys/uidinfo.h \
              src/sys/sys/uio.h \
              src/sys/sys/unistd.h \
              src/sys/sys/userconf.h \
              src/sys/sys/utsname.h \
              src/sys/sys/verified_exec.h \
              src/sys/sys/vfs_syscalls.h \
              src/sys/sys/vmem.h \
              src/sys/sys/vmem_impl.h \
              src/sys/sys/vmmeter.h \
              src/sys/sys/vnode.h \
              src/sys/sys/vnode_if.h \
              src/sys/sys/wait.h \
              src/sys/sys/wapbl.h \
              src/sys/sys/wapbl_replay.h \
              src/sys/sys/workqueue.h \
              src/sys/sys/xattr.h \
              src/sys/sys/xcall.h \
              src/sys/ufs/ext2fs/ext2fs_alloc.c \
              src/sys/ufs/ext2fs/ext2fs_balloc.c \
              src/sys/ufs/ext2fs/ext2fs_bmap.c \
              src/sys/ufs/ext2fs/ext2fs_bswap.c \
              src/sys/ufs/ext2fs/ext2fs_dinode.h \
              src/sys/ufs/ext2fs/ext2fs_dir.h \
              src/sys/ufs/ext2fs/ext2fs_extern.h \
              src/sys/ufs/ext2fs/ext2fs.h \
              src/sys/ufs/ext2fs/ext2fs_inode.c \
              src/sys/ufs/ext2fs/ext2fs_lookup.c \
              src/sys/ufs/ext2fs/ext2fs_readwrite.c \
              src/sys/ufs/ext2fs/ext2fs_rename.c \
              src/sys/ufs/ext2fs/ext2fs_subr.c \
              src/sys/ufs/ext2fs/ext2fs_vfsops.c \
              src/sys/ufs/ext2fs/ext2fs_vnops.c \
              src/sys/ufs/ffs/ffs_alloc.c \
              src/sys/ufs/ffs/ffs_appleufs.c \
              src/sys/ufs/ffs/ffs_balloc.c \
              src/sys/ufs/ffs/ffs_bswap.c \
              src/sys/ufs/ffs/ffs_extern.h \
              src/sys/ufs/ffs/ffs_inode.c \
              src/sys/ufs/ffs/ffs_quota2.c \
              src/sys/ufs/ffs/ffs_snapshot.c \
              src/sys/ufs/ffs/ffs_subr.c \
              src/sys/ufs/ffs/ffs_tables.c \
              src/sys/ufs/ffs/ffs_vfsops.c \
              src/sys/ufs/ffs/ffs_vnops.c \
              src/sys/ufs/ffs/ffs_wapbl.c \
              src/sys/ufs/ffs/fs.h \
              src/sys/ufs/lfs/lfs_extern.h \
              src/sys/ufs/lfs/lfs.h \
              src/sys/ufs/mfs/mfs_extern.h \
              src/sys/ufs/mfs/mfs_miniroot.c \
              src/sys/ufs/ufs/dinode.h \
              src/sys/ufs/ufs/dir.h \
              src/sys/ufs/ufs/dirhash.h \
              src/sys/ufs/ufs/extattr.h \
              src/sys/ufs/ufs/inode.h \
              src/sys/ufs/ufs/quota1.h \
              src/sys/ufs/ufs/quota1_subr.c \
              src/sys/ufs/ufs/quota2.h \
              src/sys/ufs/ufs/quota2_subr.c \
              src/sys/ufs/ufs/quota.h \
              src/sys/ufs/ufs/ufs_bmap.c \
              src/sys/ufs/ufs/ufs_bswap.h \
              src/sys/ufs/ufs/ufs_dirhash.c \
              src/sys/ufs/ufs/ufs_extattr.c \
              src/sys/ufs/ufs/ufs_extern.h \
              src/sys/ufs/ufs/ufs_inode.c \
              src/sys/ufs/ufs/ufs_lookup.c \
              src/sys/ufs/ufs/ufsmount.h \
              src/sys/ufs/ufs/ufs_quota2.c \
              src/sys/ufs/ufs/ufs_quota.c \
              src/sys/ufs/ufs/ufs_quota.h \
              src/sys/ufs/ufs/ufs_readwrite.c \
              src/sys/ufs/ufs/ufs_rename.c \
              src/sys/ufs/ufs/ufs_vfsops.c \
              src/sys/ufs/ufs/ufs_vnops.c \
              src/sys/ufs/ufs/ufs_wapbl.c \
              src/sys/ufs/ufs/ufs_wapbl.h \
              src/sys/uvm/uvm_amap.h \
              src/sys/uvm/uvm_anon.h \
              src/sys/uvm/uvm_aobj.c \
              src/sys/uvm/uvm_aobj.h \
              src/sys/uvm/uvm_ddb.h \
              src/sys/uvm/uvm_device.h \
              src/sys/uvm/uvm_extern.h \
              src/sys/uvm/uvm_fault.h \
              src/sys/uvm/uvm_fault_i.h \
              src/sys/uvm/uvm_glue.h \
              src/sys/uvm/uvm.h \
              src/sys/uvm/uvm_kmguard.h \
              src/sys/uvm/uvm_km.h \
              src/sys/uvm/uvm_loan.h \
              src/sys/uvm/uvm_map.h \
              src/sys/uvm/uvm_object.c \
              src/sys/uvm/uvm_object.h \
              src/sys/uvm/uvm_page.h \
              src/sys/uvm/uvm_pager.h \
              src/sys/uvm/uvm_param.h \
              src/sys/uvm/uvm_pdaemon.h \
              src/sys/uvm/uvm_pdpolicy.h \
              src/sys/uvm/uvm_pglist.h \
              src/sys/uvm/uvm_pmap.h \
              src/sys/uvm/uvm_prot.h \
              src/sys/uvm/uvm_readahead.c \
              src/sys/uvm/uvm_readahead.h \
              src/sys/uvm/uvm_stat.h \
              src/sys/uvm/uvm_swap.h \
              src/sys/uvm/uvm_swapstub.c \
              src/sys/uvm/uvm_vnode.c

MIRROR_FROM_PORT_DIR := $(addprefix src/lib/dde_rump/, $(PORT_FILES))

content: $(MIRROR_FROM_REP_DIR) $(MIRROR_FROM_PORT_DIR)

$(MIRROR_FROM_REP_DIR):
	$(mirror_from_rep_dir)

$(MIRROR_FROM_PORT_DIR):
	mkdir -p $(dir $@)
	cp -r $(PORT_DIR)/$@ $@

content: LICENSE
LICENSE:
	cp $(PORT_DIR)/src/lib/dde_rump/$@ $@
